import { PrismaClient } from '@prisma/client'
import { withAccelerate } from '@prisma/extension-accelerate'

const prisma = new PrismaClient().$extends(withAccelerate())

async function main() {
    await prisma.issue.createMany({
        data: [
        {
            title: "Vampirella #1",
            issueNumber: 1,
            year: 2010,
            size: "16.91 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-01.cbr",
            cover: "https://www.dynamite.com/images/Vampi01-cov-Ross-RareVariant.jpg",
            synopsis: "A Dynamite Entertainment tem o prazer de apresentar novamente aos leitores o flagelo dos mortos-vivos: VAMPIRELLA...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #2",
            issueNumber: 2,
            year: 2010,
            size: "16.41 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-02.cbr",
            cover: "https://www.dynamite.com/previews/C725130156938/Vampi02covJusko.jpg",
            synopsis: "Vampirella seguiu o rastro de sua presa, o sanguinário Vlad Drácula, até Seattle e um ninho cruel de vampiros que atacam os jovens e os perdidos. Nas garras de Le Fanu - um dos mais antigos e confiáveis tenentes de Drácula - Vampirella precisa enfrentar uma ameaça cada vez maior e mais aterrorizante do que qualquer outra que ela já encontrou... pois Le Fanu expôs à Vampirella seus segredos mais profundos e sombrios - a própria Vampirella (mostrada em uma história especial dentro de outra história nesta mesma edição)!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #3",
            issueNumber: 3,
            year: 2011,
            size: "16.30 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-03.cbr",
            cover: "https://www.dynamite.com/previews/C725130158840/Vampi03covChen.jpg",
            synopsis: "Vampirella está à espreita, e sua caçada a coloca frente a frente com seu nêmesis, Vlad Drácula! Mas antes de seu confronto sangrento, Vampirella precisa desvendar o mistério da Coroa de Vermes... e a solução desse quebra-cabeça pode significar sua destruição!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #4",
            issueNumber: 4,
            year: 2011,
            size: "13.35 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-04.cbr",
            cover: "https://www.dynamite.com/previews/C725130159656/Vampi04covDjurdjevic.jpg",
            synopsis: "A perseguição de Vampirella a Drácula revelou um culto de vampiros, adoradores de um mal antigo, tão vasto e terrível que até mesmo o Senhor dos Vampiros o respeita - e talvez o tema -. Enquanto o mundo se encontra entre o caos eterno e um exército interminável de horrores bebedores de sangue, Vampirella, atormentada por visões de pesadelo de seu passado e de um possível futuro, pode finalmente ter encontrado seu par.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #5",
            issueNumber: 5,
            year: 2011,
            size: "16.39 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-05.cbr",
            cover: "https://www.dynamite.com/previews/C725130162069/Vampi05covDjurdjevic.jpg",
            synopsis: "Abrindo um caminho sangrento entre as forças de Drácula, enfrentando o próprio Senhor dos Vampiros, Vampirella está agora frente a frente com um mal antigo e desconhecido, uma força aterrorizante que planeja fazer de Vampirella sua rainha eterna.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #6",
            issueNumber: 6,
            year: 2011,
            size: "16.10 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-06.cbr",
            cover: "https://www.dynamite.com/previews/C725130164629/Vampi06CovRenaud.jpg",
            synopsis: "À medida que um mal antigo e indescritível abre caminho em nosso mundo, Vampirella deve permanecer sozinha... ou tudo o que vive sofrerá e morrerá. Com os seguidores de Drácula perseguindo suas próprias agendas e legiões de horrores tentaculares de fora da realidade lutando por um ponto de apoio no plano material, apenas uma coisa é certa: haverá sangue...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #7",
            issueNumber: 7,
            year: 2011,
            size: "11.35 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-07.cbr",
            cover: "https://www.dynamite.com/previews/C725130167507/Vampi07covDjurdjevic.jpg",
            synopsis: "Seu nome é Sofia, uma jovem mulher envolvida no turbilhão de violência e terror sobrenatural que cerca a Vampirella. Ela esteve ao lado de Vampirella durante a terrível batalha contra o Lord of Worms, lutou contra as legiões sedentas de sangue de Drácula e sobreviveu às garras do vil Le Fanu. Mas quem é Sofia e que segredos se escondem em seu passado? Esta edição marca a transição para um novo - e mais sangrento - capítulo para Vampirella!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #8",
            issueNumber: 8,
            year: 2011,
            size: "11.02 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-08.cbr",
            cover: "https://www.dynamite.com/previews/C725130171153/Vampi08covDjurdjevic.jpg",
            synopsis: "Um trecho solitário de rodovia. Uma pequena cidade no meio do nada. Um trio de criaturas cruéis em uma missão de assassinato e destruição. É uma viagem de carro pela morte e pelo horror, enquanto Vampirella, ainda lidando com as consequências de sua primeira aventura, enfrenta uma ameaça que pode finalmente estar à sua altura.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #9",
            issueNumber: 9,
            year: 2011,
            size: "14.04 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-09.cbr",
            cover: "https://www.dynamite.com/previews/C725130173942/Vampi09covDjurdjevic.jpg",
            synopsis: "Em um trecho solitário de uma rodovia, Vampirella enfrenta seus inimigos mais assassinos até hoje: um trio de assassinos demoníacos, embriagados pela liberdade recém-descoberta e pela sede de sangue, com a intenção de tornar a morte da heroína vampírica algo especial",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #10",
            issueNumber: 10,
            year: 2011,
            size: "14.94 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-10.cbr",
            cover: "https://www.dynamite.com/previews/C725130175601/Vampi10covRenaud.jpg",
            synopsis: "Os Kerasu Shimei: três assassinos demoníacos, que escaparam das profundezas do inferno e pretendem construir um vil monumento ao assassinato. Tudo o que está em seu caminho? Vampirella. É o confronto final sangrento na luta mais difícil de Vampirella até agora.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #11",
            issueNumber: 11,
            year: 2011,
            size: "15.44 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-11.cbr",
            cover: "https://www.dynamite.com/previews/C725130176790/Vampi11covDjurdjevic.jpg",
            synopsis: "A caminho de sua primeira aventura internacional, Vampirella e Sofia são convocadas para o interior da Alemanha. Elas são encarregadas da segurança de uma cerimônia sagrada, mas a missão original se torna algo totalmente diferente quando elas chegam ao seu destino. É uma história alucinante de demônios, negação e medos secretos e obscuros!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #12",
            issueNumber: 12,
            year: 2011,
            size: "16.04 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-12.cbr",
            cover: "https://www.dynamite.com/previews/C725130179944/Vampi12covRenaud.jpg",
            synopsis: "A pedido não tão educado de seus misteriosos benfeitores, Vampirella e Sofia entram em um mundo maior. A caça a Vlad Drácula as leva dos EUA para a Rússia, onde um cemitério esquecido, uma igreja desconsagrada e um horror inimaginável as aguardam...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #13",
            issueNumber: 13,
            year: 2011,
            size: "16.95 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-13.cbr",
            cover: "https://www.dynamite.com/previews/C725130182104/Vampi13covReis.jpg",
            synopsis: "Em busca de um tomo perdido de conhecimento proibido, Vampirella foi atraída da Rússia para a fronteira entre a Armênia e a Turquia - e Ani, a Cidade Fantasma das 1.001 Igrejas. Outrora a sede do poder que rivalizava com Constantinopla, Ani é agora uma ruína em ruínas. E em algum lugar, no esqueleto dessa cidade morta, esconde-se a última esperança sombria de um antigo inimigo.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #14",
            issueNumber: 14,
            year: 2011,
            size: "17.12 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-14.cbr",
            cover: "https://www.dynamite.com/previews/C118406/Vampi14covRoberson.jpg",
            synopsis: "O segredo dos misteriosos benfeitores de Vampirella se aprofunda, enquanto ela luta com uma criatura lendária da mitologia em uma cidade morta. A busca de Vampirella para localizar uma relíquia há muito perdida na cidade fantasma de Ani, uma relíquia que deve ser destruída antes de desencadear um horror centenário em um mundo desavisado. Antigos acertos de contas devem ser feitos, conspirações devem ser desenterradas e, tenha certeza: haverá sangue na poeira.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella Annual #1",
            issueNumber: 15,
            year: 2011,
            size: "22.65 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-anual-01.cbr",
            cover: "https://www.dynamite.com/previews/C118407/VampiAnn01CovParrillo.jpg",
            synopsis: "A cidade de Provenance, no Kansas, pode não estar listada no mapa, mas é um local de grande significado místico - e o lar de um culto perverso que adora a Vampirella! Quando o objeto de adoração do culto chega a Provenance em busca de respostas, as coisas definitivamente vão se tornar pessoais... e sangrentas. Há surpresas nas sombras, escolhas a serem feitas... e alguém mais está ouvindo sinos de casamento? Espero que Vampi já tenha escolhido um vestido.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #15",
            issueNumber: 16,
            year: 2012,
            size: "13.49 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-15.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406101511/Vampi15covRenaud.jpg",
            synopsis: "Nas profundezas em ruínas de uma cidade esquecida e morta, Vampirella e sua aliada humana, Sofia Murray, enfrentam um bando de lobisomens russos, um fantasma que se alimenta de culpa e o plano final de um velho inimigo: o sinistro Von Kreist. E, desta vez, o preço da vitória pode ser mais do que até mesmo Vampirella pode suportar. Segredos são revelados, confidências são traídas e uma conspiração há muito adormecida dá frutos sinistros...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #16",
            issueNumber: 17,
            year: 2012,
            size: "16.43 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-16.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406101611/Vampi16covRenaud.jpg",
            synopsis: "Em uma cidade antiga e abandonada, Vampirella enfrenta a traição de um aliado, uma perda terrível e o retorno de um antigo inimigo. Não perca o capítulo mais sombrio até agora na aclamada série de horror-aventura da Dynamite Entertainment.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #17",
            issueNumber: 18,
            year: 2012,
            size: "15.88 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-17.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406101711/Vampi17covParrillo.jpg",
            synopsis: "A caçada de Vampirella a um assassino em série sobrenatural em meio às ruínas de uma cidade fantasma levou a uma traição total, uma perda terrível e o retorno de um antigo inimigo: o sinistro Von Kreist. Uma equipe de caçadores de monstros - o grupo de ação secreta do Vaticano, \"Cestus Dei\" - chegou para controlar a cena por todos os meios necessários. Mas será que eles verão Vampirella como amiga... ou inimiga?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #18",
            issueNumber: 19,
            year: 2012,
            size: "20.47 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-18.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406101811/Vampi18covParrillo.jpg",
            synopsis: "Vampirella - ainda abalada pelo terrível destino de sua aliada Sofia e pelo renascimento de seu antigo inimigo, Von Kriest - volta à batalha quando mais antigos inimigos ressurgem, alguns oferecendo uma trégua. Mas será que o inimigo de seu inimigo é realmente um amigo?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #19",
            issueNumber: 20,
            year: 2012,
            size: "21.50 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-19.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406101911/Vampi19covRisqueIncen.jpg",
            synopsis: "Velhos inimigos ressurgem, Drácula está à espreita e Vampirella luta contra as maquinações de seus inimigos e de seus supostos aliados, \"Cestus Dei\". E, em meio a intrigas e violência, um esquema aterrorizante, arquitetado sob a cidade de Seattle, está prestes a lançar tudo o que vive em um mar de sangue.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #20",
            issueNumber: 21,
            year: 2012,
            size: "18.80 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-20.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102011/Vampi20covRenaud.jpg",
            synopsis: "É um confronto sangrento entre Drácula e a ala paramilitar do Vaticano, \"Cestus Dei\". Vlad tem novos truques na manga, alianças com deuses antigos que fazem a Ordem e o Caos tremerem, e seus planos de conquista profana estão à beira do sucesso. É claro que Vampirella pode ter algo a dizer sobre isso.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #21",
            issueNumber: 22,
            year: 2012,
            size: "18.32 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-21.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102111/Vampi21covRenaudBurst.jpg",
            synopsis: "Após os eventos surpreendentes da última edição, Vampirella está pronta para colocar tudo em risco em uma tentativa de salvar uma alma e destruir outra. Tanto os heróis quanto os vilões estão jogando para o seu próprio fim, e as cartas estão virando com uma rapidez mortal. Não estamos brincando quando dizemos que GRANDES mudanças estão chegando, e tudo começa aqui com a Parte 1 de INQUISIÇÃO!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella Annual #2",
            issueNumber: 23,
            year: 2012,
            size: "20.77 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-anual-02.cbr",
            cover: "https://www.dynamite.com/previews/C72513018407800211/VampiAnn02CovLinsner.jpg",
            synopsis: "Um jovem e ávido fã quer ser o novo parceiro de Vampi e, contra seu bom senso, ela vai com ele a uma cena realmente perturbadora: uma pequena cidade que realiza uma convenção para uma série popular de livros e filmes de vampiros. Enquanto a cidade se esforça absurdamente para lucrar com os fãs.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #22",
            issueNumber: 24,
            year: 2012,
            size: "17.10 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-22.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102211/Vampi22covRenaud.jpg",
            synopsis: "INQUISIÇÃO continua aqui! Há uma revolução se formando nas profundezas da Cidade do Vaticano, e Vampirella é pega no fogo cruzado! De que lado você fica quando não pode confiar em ninguém?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #23",
            issueNumber: 25,
            year: 2012,
            size: "17.53 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-23.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102311/Vampi23covRenaud.jpg",
            synopsis: "A história de \"INQUISIÇÃO\" chega à sua dramática conclusão nesta edição! Vampirella precisa defender suas ações recentes e provar que não foi corrompida pela influência do Caos... antes que seu inimigo mais poderoso a leve à loucura! O equilíbrio do universo está sobre os ombros de Vampirella, e o peso pode ser demais para ela suportar!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #24",
            issueNumber: 26,
            year: 2012,
            size: "13.55 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-24.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102411/Vampi24covRenaud.jpg",
            synopsis: "As linhas de batalha foram traçadas! Os terríveis soldados de Drácula - e seu novo tenente - estão na ofensiva, mas eles terão que passar por Vampirella e seus aliados! O épico INFERNO NA TERRA, em duas partes, começa aqui! ",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #25",
            issueNumber: 27,
            year: 2012,
            size: "17.64 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-25.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102511/Vampi25covRenaud.jpg",
            synopsis: "INFERNO NA TERRA termina aqui, encerrando o segundo ano da série Vampirella da Dynamite! Os dois vampiros mais poderosos da Terra estão se enfrentando em uma fúria de sangue e fogo, e o equilíbrio do Caos e da Ordem está em jogo!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #26",
            issueNumber: 28,
            year: 2012,
            size: "23.47 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-26.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102611/Vampi26covParrillo.jpg",
            synopsis: "O terceiro ano da Vampirella da Dynamite começa aqui! Há um novo amanhecer na Terra e um novo começo para Vampirella após a guerra. Quem são Mother Rowan e os Sleepless Boys, e por que eles pediram a ajuda de nossa heroína? Um livro da Dynamite, perfeito para fãs de longa data e novos leitores!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #27",
            issueNumber: 29,
            year: 2013,
            size: "26.39 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-27.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102711/Vampi27covRenaud.jpg",
            synopsis: "A história em duas partes \"Teorias da Relatividade\" começa aqui! Segredos - e talvez um pouco de sangue - certamente serão derramados quando Vampirella se encontrar no meio de uma inesperada reunião de família. As revelações não param por aí, também estamos puxando a cortina para revelar as histórias de origem de Criswell e The Conjuress! Como eles estão ligados e o que o vínculo deles tem a ver com a mãe de Vampirella, Lilith?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #28",
            issueNumber: 30,
            year: 2013,
            size: "11.47 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-28.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102811/Vampi28covParrillo.jpg",
            synopsis: "\"Teorias da Relatividade\" (Parte 2 de 2): A mãe de Vampirella, Lilith, afirma que não é a mesma manipuladora maligna que costumava ser, e está disposta a ir a grandes distâncias... ou seja, profundidades... para provar isso! Também nesta edição: As histórias de origem de Criswell e The Conjuress são concluídas!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #29",
            issueNumber: 31,
            year: 2013,
            size: "9.65 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-29.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406102911/Vampi29covRenaud.jpg",
            synopsis: "\"Prepare os controles para o coração do sol\" (Parte 1 de 3) - Depois de ficar um pouco dispersa, a Equipe Vampirella está reunida com um novo propósito. Isso também é bom, pois a equipe terá muito trabalho para combater um grupo de bruxas no presente, enquanto Vampirella e Criswell estão ocupados. E por \"ocupados\", queremos dizer que suas mentes foram projetadas 100 anos no futuro!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #30",
            issueNumber: 32,
            year: 2013,
            size: "9.10 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-30.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103011/Vampi30covParrillo.jpg",
            synopsis: "Vampirella e Criswell estão presos cem anos no futuro, desvendando um mistério de proporções apocalípticas. Enquanto isso, no presente, seus aliados lutam contra um grupo mortal de bruxas cujos terríveis feitiços ameaçam danificar todo o tempo e a realidade! Variante: Capa de Renaud. Consulte o varejista local para saber a disponibilidade.",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #31",
            issueNumber: 33,
            year: 2013,
            size: "8.43 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-31.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103111/Vampi31covParrillo.jpg",
            synopsis: "Dizem que você nunca deve saber seu próprio futuro... mas e se você souber? Decisões serão tomadas, destinos serão cumpridos e um reino se erguerá! Mas será que Vampirella terá forças para suportar o doloroso preço da vitória?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #32",
            issueNumber: 34,
            year: 2013,
            size: "9.62 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-32.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103211/Vampi32covNeves.jpg",
            synopsis: "Vampirella encontra o terror no coração de Cote de Soleil, uma nação insular com segredos sombrios de Voudon... e isso não é tudo! Um adversário clássico dos vampiros pode estar se escondendo nas sombras e esperando o momento perfeito para atacar!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #33",
            issueNumber: 35,
            year: 2013,
            size: "11.83 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-33.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103311/Vampi33covParrillo.jpg",
            synopsis: "Na ilha de Cote de Soleil, um mal antigo e morto retornou para recuperar um poder há muito perdido... e essa não é a única coisa sinistra que está rastejando por aí. A transformação é o nome do jogo quando Vampirella e o vodu se enfrentam na selva!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #34",
            issueNumber: 36,
            year: 2013,
            size: "9.76 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-34.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103411/Vampi34covParrillo.jpg",
            synopsis: "Tendo vislumbrado um possível futuro, Vampirella faz uma grande escolha para si mesma: ela se tornará a Santa Padroeira dos Monstros e começará construindo um local de refúgio para os estranhos e medrosos. O caminho para o inferno é pavimentado com boas intenções...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #35",
            issueNumber: 37,
            year: 2013,
            size: "9.78 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-35.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103511/Vampi35covParrillo.jpg",
            synopsis: "\"Ela Vende Santuário\" (Parte 2 de 2) Após um ataque surpresa de um novo inimigo, Vampirella toma uma decisão chocante. Quem é a Irmã Meia-Noite e por que ela quer a Vampirella morta? Até onde nossa heroína irá para defender sua visão de um futuro melhor? E qual será a posição de Adam Van Helsing depois disso? As respostas estão à sua espera...",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #36",
            issueNumber: 38,
            year: 2013,
            size: "8.84 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-36.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103611/Vampi36covParrillo.jpg",
            synopsis: "O novo papel de liderança de Vampirella no mundo dos monstros tem sido tanto um catalisador de divisão quanto de união. Mesmo com suas recentes vitórias, há quem acredite que ela está seguindo o caminho errado... e Adam Van Helsing decidiu que é hora de informá-la. A honestidade é a chave para um relacionamento saudável, certo?",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #37",
            issueNumber: 39,
            year: 2013,
            size: "8.98 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-37.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103711/Vampi37covParrillo.jpg",
            synopsis: "Lilith tem um segredo guardado, e ela não é a única. Quando a verdade vier à tona, Vampirella dará a sua mãe o benefício da dúvida... especialmente se o segredo de Lilith diz respeito a alguns dos inimigos mais sinistros de Vampi? As respostas para algumas perguntas persistentes aguardam nesta edição!",
            comicId: 1,
            idiomId: 1,
        },
        {
            title: "Vampirella #38",
            issueNumber: 40,
            year: 2014,
            size: "13.50 MB",
            series: "Vampirella (2010)",
            genres: "Horror, Super Herói",
            link: "/uploads/vampirella/vampirella-38.cbr",
            cover: "https://www.dynamite.com/previews/C72513018406103811/Vampi38covParrillo.jpg",
            synopsis: "Tranquem as portas e fechem as cortinas, leitores fiéis. Chegou a hora de A Última História da Vampirella. Quem está contando? Quem está ouvindo? E quem viu isso chegando antes de qualquer um? O que será de nossa querida Vampirella e sua vasta gama de amigos, inimigos e membros da família? É o fim do mundo como o conhecemos... por enquanto.",
            comicId: 1,
            idiomId: 1,
        },
    ]
    });

    console.log('✅ Issues criados com sucesso!');
}

main()
    .catch((e) => {
        console.error('❌ Erro ao criar issues:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });