import { prisma } from '../src/lib/db';

async function main() {
    await prisma.issue.createMany({
        data: [
            {
                title: "Fatale #1",
                issueNumber: 1,
                year: 2012,
                size: "17.04 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-01.cbr",
                cover: "public/assets/covers/fatale/fatale-01.webp",
                synopsis: "Um repórter em 2012 descobre um segredo que o leva ao caminho mais sombrio que se possa imaginar... a uma mulher sedutora que está foragida desde 1935, um mafioso que pode ser um monstro demoníaco imortal e as histórias de todos os homens condenados que foram pegos em sua luta de décadas.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #2",
                issueNumber: 2,
                year: 2012,
                size: "16.30 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-02.cbr",
                cover: "public/assets/covers/fatale/fatale-02.webp",
                synopsis: "A segunda edição da série mais quente de 2012 está aqui! Nos tempos modernos, Nicholas Lash busca respostas sobre a mulher misteriosa que arruinou sua vida, enquanto, em meados da década de 1950, o repórter Dominic Raines é levado pelo mesmo caminho assassino... A premiada equipe de Brubaker e Phillips mantém o calor em alta neste épico horror noir.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #3",
                issueNumber: 3,
                year: 2012,
                size: "16.91 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-03.cbr",
                cover: "public/assets/covers/fatale/fatale-03.webp",
                synopsis: "O que o detetive Walt Booker sacrificará e a quais deuses? Ele está buscando redenção ou vingança? Na terceira parte da nova obra-prima de terror/noir de BRUBAKER e PHILLIPS, os fios do primeiro arco se entrelaçam... em um nó em volta do pescoço de um policial corrupto na São Francisco do final dos anos 50.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #4",
                issueNumber: 4,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-04.cbr",
                cover: "public/assets/covers/fatale/fatale-04.webp",
                synopsis: "O sucesso surpresa de 2012 continua! O primeiro arco de FATALE se encaminha perigosamente para seu final esmagador... todas as peças estão no lugar, Josephine e seu amante estão preparados para executar seu plano, mas apenas um deles sabe com que tipo de homens (ou demônios) estão lidando. Nada sairá como planejado, e haverá sangue.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #5",
                issueNumber: 5,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-05.cbr",
                cover: "public/assets/covers/fatale/fatale-05.webp",
                synopsis: "O sucesso surpresa de 2012 continua! O primeiro arco de FATALE se encaminha perigosamente para seu final esmagador... todas as peças estão no lugar, Josephine e seu amante estão preparados para executar seu plano, mas apenas um deles sabe com que tipo de homens (ou demônios) estão lidando. Nada sairá como planejado, e haverá sangue.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #6",
                issueNumber: 6,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-06.cbr",
                cover: "public/assets/covers/fatale/fatale-06.webp",
                synopsis: "O segundo arco de FATALE começa aqui! Nos tempos modernos, Nicolas Lash busca mais informações sobre a misteriosa Josephine... enquanto em meados da década de 1970, em Los Angeles, Jo está tentando estabelecer uma nova vida. Mas esta é a Los Angeles pós-amor livre, pós-Família Manson, e as colinas de Hollywood têm seus próprios segredos obscuros. A obra-prima de horror noir de BRUBAKER e PHILLIPS continua!",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #7",
                issueNumber: 7,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-07.cbr",
                cover: "public/assets/covers/fatale/fatale-07.webp",
                synopsis: "A série ocultista noir mais vendida de BRUBAKER e PHILLIPS continua seu segundo arco, quando os segredos obscuros de Los Angeles de meados dos anos 70 começam a se infiltrar na nova vida de Josephine. Drogas, sexo, cultos, fama e assassinato, todos caminham lado a lado à sombra de forças demoníacas.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #8",
                issueNumber: 8,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-08.cbr",
                cover: "public/assets/covers/fatale/fatale-08.webp",
                synopsis: "É o ponto de virada do segundo arco da série FATALE de BRUBAKER & PHILLIPS! Qual é o plano secreto de Josephine e o que ela tem feito durante todos esses anos em fuga, desde os anos 50 até o final dos anos 70? Será que o monstro que a perseguiu a maior parte de sua vida voltou?",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #9",
                issueNumber: 9,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-09.cbr",
                cover: "public/assets/covers/fatale/fatale-09.webp",
                synopsis: "O segundo arco de FATALE, “The Devil's Business”, se aproxima do clímax quando Jo sai do esconderijo, pronta para enfrentar o Bishop ressuscitado, enquanto seus cultistas vasculham a Hollywood dos anos 1970 em busca dela e de seu novo amante.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #10",
                issueNumber: 10,
                year: 2012,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-10.cbr",
                cover: "public/assets/covers/fatale/fatale-10.webp",
                synopsis: "O segundo arco de FATALE chega à sua conclusão brutal!Segredos são revelados e novos mistérios nascem, enquanto nossa estrela Femme Fatale passa de vítima a heroína!",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #11",
                issueNumber: 11,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-11.cbr",
                cover: "public/assets/covers/fatale/fatale-11.webp",
                synopsis: "Esta é a primeira de quatro edições autônomas do FATALE FLASHBACK, e é o lugar perfeito para novos leitores embarcarem! Bem-vindo à Califórnia dos anos 1930, onde é difícil ser uma garota em fuga. Testemunhe os primeiros dias de Josephine com a maldição da femme fatale e descubra alguns de seus segredos.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #12",
                issueNumber: 12,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-12.cbr",
                cover: "public/assets/covers/fatale/fatale-12.webp",
                synopsis: "A maldição da Femme Fatale data de muito antes de Josephine. Agora, voltamos aos tempos medievais e à história de uma jovem guerreira que enfrenta um horror indescritível que reverbera através dos tempos! Essa é outra edição autônoma do FATALE FLASHBACK e o lugar perfeito para os novos leitores começarem!",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #13",
                issueNumber: 13,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-13.cbr",
                cover: "public/assets/covers/fatale/fatale-13.webp",
                synopsis: "Prepare-se para ser cativado pelo fascínio da Femme Fatale no oeste selvagem, uma adição emocionante para os fãs de horror e noir em seus westerns spaghetti. Outra edição autônoma de FATALE FLASHBACK! Este é o lugar perfeito para novos leitores embarcarem!",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #14",
                issueNumber: 14,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-14.cbr",
                cover: "public/assets/covers/fatale/fatale-14.webp",
                synopsis: "A última edição autônoma do FATALE FLASHBACK é a Segunda Guerra Mundial! Cultistas e monstros nazistas estão perseguindo Jo, que busca respostas e encontra o Sr. Bishop cara a cara pela primeira vez.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #15",
                issueNumber: 15,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-15.cbr",
                cover: "public/assets/covers/fatale/fatale-15.webp",
                synopsis: "UM NOVO ARCO COMEÇA! FATALE finalmente chega aos tempos modernos, quando a pesquisa de Nicolas Lash em sua cela de prisão atrai velhos inimigos. E ele não tem mais para onde fugir.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #16",
                issueNumber: 16,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-16.cbr",
                cover: "public/assets/covers/fatale/fatale-16.webp",
                synopsis: "Nicolas está na trilha dos segredos de Josephine, e eles o levam de volta à Seattle dos anos 90, onde uma banda de rock, uma gangue de ladrões de banco e um assassino em série errante circulam em torno de uma mulher misteriosa e sem memória...",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #17",
                issueNumber: 17,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-17.cbr",
                cover: "public/assets/covers/fatale/fatale-17.webp",
                synopsis: "O Bishop desapareceu em Los Angeles no final dos anos 70, em um grito ardente, mas ele nunca foi embora de verdade, e agora ele finalmente tem o cheiro de Jo novamente.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #18",
                issueNumber: 18,
                year: 2013,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-18.cbr",
                cover: "public/assets/covers/fatale/fatale-18.webp",
                synopsis: "INDICADA A MAIS PRÊMIOS EISNER 2013 DO QUE QUALQUER OUTRA HISTÓRIA EM QUADRINHOS! Tudo dá errado quando Josephine aparece em um videoclipe de uma banda de Seattle, e seu efeito sobre aqueles que a desejam se torna selvagem, enquanto o arco mais emocionante de Fatale continua.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #19",
                issueNumber: 19,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-19.cbr",
                cover: "public/assets/covers/fatale/fatale-19.webp",
                synopsis: "Rock 'n' roll, roubo e assassinato ritual se chocam na Seattle dos anos 90, quando o quarto arco de FATALE chega a uma conclusão devastadora... e a identidade secreta do ajudante atual de Nic é revelada. Será que ele é quem diz ser?",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #20",
                issueNumber: 20,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-20.cbr",
                cover: "public/assets/covers/fatale/fatale-20.webp",
                synopsis: "NOVO ARCO DE HISTÓRIA! Nicolas Lash está na maior enrascada possível, e só há uma pessoa que pode salvá-lo agora... o problema é que a enrascada é problema dela.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #21",
                issueNumber: 21,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-21.cbr",
                cover: "public/assets/covers/fatale/fatale-21.webp",
                synopsis: "Parte dois do arco mais intenso de FATALE até agora! Nicolas Lash e Josephine finalmente se reencontram, e tudo o que sabemos sobre a Fatale é virado de cabeça para baixo... ",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #22",
                issueNumber: 22,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-22.cbr",
                cover: "public/assets/covers/fatale/fatale-22.webp",
                synopsis: "A história da vida do homem-monstro chamado The Bishop.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #23",
                issueNumber: 23,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-23.cbr",
                cover: "public/assets/covers/fatale/fatale-23.webp",
                synopsis: "A edição mais estranha de FATALE até agora, quando Nicolas Lash finalmente descobre os últimos segredos de Josephine, e o universo nunca mais será o mesmo.",
                comicId: 3,
                idiomId: 1,
            },
            {
                title: "Fatale #24",
                issueNumber: 24,
                year: 2014,
                size: "16.35 MB",
                series: "Fatale (2012)",
                genres: "Crime",
                link: "assets/uploads/fatale/fatale-24.cbr",
                cover: "public/assets/covers/fatale/fatale-24.webp",
                synopsis: "TUDO TERMINA AQUI! A última edição extra longa de FATALE! Há tanta história que precisávamos de muito mais espaço. Os últimos segredos de Josephine serão revelados? Haverá muita tragédia? SIM!",
                comicId: 3,
                idiomId: 1,
            },
        ]
    });

    console.log('✅ Issues de Fatale (2012) criadas com sucesso!');
}

main()
    .catch((e) => {
        console.error('❌ Erro ao criar issues:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });